# Exoplanet AI Detector Configuration
# NASA Space Apps Challenge 2025

# Data paths
data:
  raw_dir: "data/raw"
  processed_dir: "data/processed"
  external_dir: "data/external"

# Model parameters
models:
  cnn:
    input_size: 1024
    hidden_layers: [128, 64, 32]
    dropout: 0.3
    learning_rate: 0.001
    
  random_forest:
    n_estimators: 100
    max_depth: 10
    random_state: 42

# Training settings
training:
  batch_size: 32
  epochs: 50
  validation_split: 0.2
  test_split: 0.2

# Data processing
preprocessing:
  normalize: true
  remove_outliers: true
  filter_threshold: 3.0
